#include <string.h>
#include <stdbool.h>
#include <unicorn/unicorn.h>
#include "../utils.h"
#include "../unicorn_consts.h"
#include "../configuration.h"
#include "unicorn_consts_riscv.h"

uint64_t uc_cpu_from_name_riscv(const char* cpu_name)
{
    static unicorn_const_t const cpu_array[]=
    {  
        {"ANY",UC_CPU_RISCV32_ANY},{"BASE32",UC_CPU_RISCV32_BASE32},{"SIFIVE_E31",UC_CPU_RISCV32_SIFIVE_E31},{"SIFIVE_U34",UC_CPU_RISCV32_SIFIVE_U34}
    };

    const int numEntries=sizeof(cpu_array) / sizeof(cpu_array[0]);
    for (int i=0;i<numEntries;i++)
    {
        if (strcasecmp(cpu_name,cpu_array[i].name) == 0)
        {
            return cpu_array[i].unicorn_value;
        }

    }
    fprintf(stderr, "Error %s is not a valid CPU for riscv.\n",cpu_name);
    fprintf(stderr, "Valid choices are:");
    for (int i=0;i<numEntries;i++)
    {
        fprintf(stderr, "%s ",cpu_array[i].name);
    }
    fprintf(stderr, "\n");
    my_exit(-1);
    return 666;  /// just here to keep the compiler happy. 
}


uint64_t uc_reg_from_int_riscv(uint64_t index)
{
    static unicorn_const_t const register_array[]=
    {
        {"X1",UC_RISCV_REG_X1},{"X2",UC_RISCV_REG_X2},{"X3",UC_RISCV_REG_X3},{"X4",UC_RISCV_REG_X4},{"X5",UC_RISCV_REG_X5},{"X0",UC_RISCV_REG_X0},{"X6",UC_RISCV_REG_X6},{"X7",UC_RISCV_REG_X7},{"X8",UC_RISCV_REG_X8},{"X9",UC_RISCV_REG_X9},{"X10",UC_RISCV_REG_X10},{"X11",UC_RISCV_REG_X11},{"X12",UC_RISCV_REG_X12},{"X13",UC_RISCV_REG_X13},{"X14",UC_RISCV_REG_X14},{"X15",UC_RISCV_REG_X15},{"X16",UC_RISCV_REG_X16},{"X17",UC_RISCV_REG_X17},{"X18",UC_RISCV_REG_X18},{"X19",UC_RISCV_REG_X19},{"X20",UC_RISCV_REG_X20},{"X21",UC_RISCV_REG_X21},{"X22",UC_RISCV_REG_X22},{"X23",UC_RISCV_REG_X23},{"X24",UC_RISCV_REG_X24},{"X25",UC_RISCV_REG_X25},{"X26",UC_RISCV_REG_X26},{"X27",UC_RISCV_REG_X27},{"X28",UC_RISCV_REG_X28},{"X29",UC_RISCV_REG_X29},{"X30",UC_RISCV_REG_X30},{"X31",UC_RISCV_REG_X31},{"USTATUS",UC_RISCV_REG_USTATUS},{"UIE",UC_RISCV_REG_UIE},{"UTVEC",UC_RISCV_REG_UTVEC},{"USCRATCH",UC_RISCV_REG_USCRATCH},{"UEPC",UC_RISCV_REG_UEPC},{"UCAUSE",UC_RISCV_REG_UCAUSE},{"UTVAL",UC_RISCV_REG_UTVAL},{"UIP",UC_RISCV_REG_UIP},{"FFLAGS",UC_RISCV_REG_FFLAGS},{"FRM",UC_RISCV_REG_FRM},{"FCSR",UC_RISCV_REG_FCSR},{"CYCLE",UC_RISCV_REG_CYCLE},{"TIME",UC_RISCV_REG_TIME},{"INSTRET",UC_RISCV_REG_INSTRET},{"HPMCOUNTER3",UC_RISCV_REG_HPMCOUNTER3},{"HPMCOUNTER4",UC_RISCV_REG_HPMCOUNTER4},{"HPMCOUNTER5",UC_RISCV_REG_HPMCOUNTER5},{"HPMCOUNTER6",UC_RISCV_REG_HPMCOUNTER6},{"HPMCOUNTER7",UC_RISCV_REG_HPMCOUNTER7},{"HPMCOUNTER8",UC_RISCV_REG_HPMCOUNTER8},{"HPMCOUNTER9",UC_RISCV_REG_HPMCOUNTER9},{"HPMCOUNTER10",UC_RISCV_REG_HPMCOUNTER10},{"HPMCOUNTER11",UC_RISCV_REG_HPMCOUNTER11},{"HPMCOUNTER12",UC_RISCV_REG_HPMCOUNTER12},{"HPMCOUNTER13",UC_RISCV_REG_HPMCOUNTER13},{"HPMCOUNTER14",UC_RISCV_REG_HPMCOUNTER14},{"HPMCOUNTER15",UC_RISCV_REG_HPMCOUNTER15},{"HPMCOUNTER16",UC_RISCV_REG_HPMCOUNTER16},{"HPMCOUNTER17",UC_RISCV_REG_HPMCOUNTER17},{"HPMCOUNTER18",UC_RISCV_REG_HPMCOUNTER18},{"HPMCOUNTER19",UC_RISCV_REG_HPMCOUNTER19},{"HPMCOUNTER20",UC_RISCV_REG_HPMCOUNTER20},{"HPMCOUNTER21",UC_RISCV_REG_HPMCOUNTER21},{"HPMCOUNTER22",UC_RISCV_REG_HPMCOUNTER22},{"HPMCOUNTER23",UC_RISCV_REG_HPMCOUNTER23},{"HPMCOUNTER24",UC_RISCV_REG_HPMCOUNTER24},{"HPMCOUNTER25",UC_RISCV_REG_HPMCOUNTER25},{"HPMCOUNTER26",UC_RISCV_REG_HPMCOUNTER26},{"HPMCOUNTER27",UC_RISCV_REG_HPMCOUNTER27},{"HPMCOUNTER28",UC_RISCV_REG_HPMCOUNTER28},{"HPMCOUNTER29",UC_RISCV_REG_HPMCOUNTER29},{"HPMCOUNTER30",UC_RISCV_REG_HPMCOUNTER30},{"HPMCOUNTER31",UC_RISCV_REG_HPMCOUNTER31},{"CYCLEH",UC_RISCV_REG_CYCLEH},{"TIMEH",UC_RISCV_REG_TIMEH},{"INSTRETH",UC_RISCV_REG_INSTRETH},{"MCYCLE",UC_RISCV_REG_MCYCLE},{"MINSTRET",UC_RISCV_REG_MINSTRET},{"MCYCLEH",UC_RISCV_REG_MCYCLEH},{"MINSTRETH",UC_RISCV_REG_MINSTRETH},{"MVENDORID",UC_RISCV_REG_MVENDORID},{"MARCHID",UC_RISCV_REG_MARCHID},{"MIMPID",UC_RISCV_REG_MIMPID},{"MHARTID",UC_RISCV_REG_MHARTID},{"MSTATUS",UC_RISCV_REG_MSTATUS},{"MISA",UC_RISCV_REG_MISA},{"MEDELEG",UC_RISCV_REG_MEDELEG},{"MIDELEG",UC_RISCV_REG_MIDELEG},{"MIE",UC_RISCV_REG_MIE},{"MTVEC",UC_RISCV_REG_MTVEC},{"MCOUNTEREN",UC_RISCV_REG_MCOUNTEREN},{"MSTATUSH",UC_RISCV_REG_MSTATUSH},{"MUCOUNTEREN",UC_RISCV_REG_MUCOUNTEREN},{"MSCOUNTEREN",UC_RISCV_REG_MSCOUNTEREN},{"MHCOUNTEREN",UC_RISCV_REG_MHCOUNTEREN},{"MSCRATCH",UC_RISCV_REG_MSCRATCH},{"MEPC",UC_RISCV_REG_MEPC},{"MCAUSE",UC_RISCV_REG_MCAUSE},{"MTVAL",UC_RISCV_REG_MTVAL},{"MIP",UC_RISCV_REG_MIP},{"MBADADDR",UC_RISCV_REG_MBADADDR},{"SSTATUS",UC_RISCV_REG_SSTATUS},{"SEDELEG",UC_RISCV_REG_SEDELEG},{"SIDELEG",UC_RISCV_REG_SIDELEG},{"SIE",UC_RISCV_REG_SIE},{"STVEC",UC_RISCV_REG_STVEC},{"SCOUNTEREN",UC_RISCV_REG_SCOUNTEREN},{"SSCRATCH",UC_RISCV_REG_SSCRATCH},{"SEPC",UC_RISCV_REG_SEPC},{"SCAUSE",UC_RISCV_REG_SCAUSE},{"STVAL",UC_RISCV_REG_STVAL},{"SIP",UC_RISCV_REG_SIP},{"SBADADDR",UC_RISCV_REG_SBADADDR},{"SPTBR",UC_RISCV_REG_SPTBR},{"SATP",UC_RISCV_REG_SATP},{"HSTATUS",UC_RISCV_REG_HSTATUS},{"HEDELEG",UC_RISCV_REG_HEDELEG},{"HIDELEG",UC_RISCV_REG_HIDELEG},{"HIE",UC_RISCV_REG_HIE},{"HCOUNTEREN",UC_RISCV_REG_HCOUNTEREN},{"HTVAL",UC_RISCV_REG_HTVAL},{"HIP",UC_RISCV_REG_HIP},{"HTINST",UC_RISCV_REG_HTINST},{"HGATP",UC_RISCV_REG_HGATP},{"PC",UC_RISCV_REG_PC}
    };

    const int numEntries=sizeof(register_array) / sizeof(register_array[0]);
    return index < numEntries ? register_array[index].unicorn_value : UC_RISCV_REG_INVALID;
}

const char* register_name_from_int_riscv(uint64_t index)
{
    static unicorn_const_t const register_array[]=
    {
        {"X1",UC_RISCV_REG_X1},{"X2",UC_RISCV_REG_X2},{"X3",UC_RISCV_REG_X3},{"X4",UC_RISCV_REG_X4},{"X5",UC_RISCV_REG_X5},{"X0",UC_RISCV_REG_X0},{"X6",UC_RISCV_REG_X6},{"X7",UC_RISCV_REG_X7},{"X8",UC_RISCV_REG_X8},{"X9",UC_RISCV_REG_X9},{"X10",UC_RISCV_REG_X10},{"X11",UC_RISCV_REG_X11},{"X12",UC_RISCV_REG_X12},{"X13",UC_RISCV_REG_X13},{"X14",UC_RISCV_REG_X14},{"X15",UC_RISCV_REG_X15},{"X16",UC_RISCV_REG_X16},{"X17",UC_RISCV_REG_X17},{"X18",UC_RISCV_REG_X18},{"X19",UC_RISCV_REG_X19},{"X20",UC_RISCV_REG_X20},{"X21",UC_RISCV_REG_X21},{"X22",UC_RISCV_REG_X22},{"X23",UC_RISCV_REG_X23},{"X24",UC_RISCV_REG_X24},{"X25",UC_RISCV_REG_X25},{"X26",UC_RISCV_REG_X26},{"X27",UC_RISCV_REG_X27},{"X28",UC_RISCV_REG_X28},{"X29",UC_RISCV_REG_X29},{"X30",UC_RISCV_REG_X30},{"X31",UC_RISCV_REG_X31},{"USTATUS",UC_RISCV_REG_USTATUS},{"UIE",UC_RISCV_REG_UIE},{"UTVEC",UC_RISCV_REG_UTVEC},{"USCRATCH",UC_RISCV_REG_USCRATCH},{"UEPC",UC_RISCV_REG_UEPC},{"UCAUSE",UC_RISCV_REG_UCAUSE},{"UTVAL",UC_RISCV_REG_UTVAL},{"UIP",UC_RISCV_REG_UIP},{"FFLAGS",UC_RISCV_REG_FFLAGS},{"FRM",UC_RISCV_REG_FRM},{"FCSR",UC_RISCV_REG_FCSR},{"CYCLE",UC_RISCV_REG_CYCLE},{"TIME",UC_RISCV_REG_TIME},{"INSTRET",UC_RISCV_REG_INSTRET},{"HPMCOUNTER3",UC_RISCV_REG_HPMCOUNTER3},{"HPMCOUNTER4",UC_RISCV_REG_HPMCOUNTER4},{"HPMCOUNTER5",UC_RISCV_REG_HPMCOUNTER5},{"HPMCOUNTER6",UC_RISCV_REG_HPMCOUNTER6},{"HPMCOUNTER7",UC_RISCV_REG_HPMCOUNTER7},{"HPMCOUNTER8",UC_RISCV_REG_HPMCOUNTER8},{"HPMCOUNTER9",UC_RISCV_REG_HPMCOUNTER9},{"HPMCOUNTER10",UC_RISCV_REG_HPMCOUNTER10},{"HPMCOUNTER11",UC_RISCV_REG_HPMCOUNTER11},{"HPMCOUNTER12",UC_RISCV_REG_HPMCOUNTER12},{"HPMCOUNTER13",UC_RISCV_REG_HPMCOUNTER13},{"HPMCOUNTER14",UC_RISCV_REG_HPMCOUNTER14},{"HPMCOUNTER15",UC_RISCV_REG_HPMCOUNTER15},{"HPMCOUNTER16",UC_RISCV_REG_HPMCOUNTER16},{"HPMCOUNTER17",UC_RISCV_REG_HPMCOUNTER17},{"HPMCOUNTER18",UC_RISCV_REG_HPMCOUNTER18},{"HPMCOUNTER19",UC_RISCV_REG_HPMCOUNTER19},{"HPMCOUNTER20",UC_RISCV_REG_HPMCOUNTER20},{"HPMCOUNTER21",UC_RISCV_REG_HPMCOUNTER21},{"HPMCOUNTER22",UC_RISCV_REG_HPMCOUNTER22},{"HPMCOUNTER23",UC_RISCV_REG_HPMCOUNTER23},{"HPMCOUNTER24",UC_RISCV_REG_HPMCOUNTER24},{"HPMCOUNTER25",UC_RISCV_REG_HPMCOUNTER25},{"HPMCOUNTER26",UC_RISCV_REG_HPMCOUNTER26},{"HPMCOUNTER27",UC_RISCV_REG_HPMCOUNTER27},{"HPMCOUNTER28",UC_RISCV_REG_HPMCOUNTER28},{"HPMCOUNTER29",UC_RISCV_REG_HPMCOUNTER29},{"HPMCOUNTER30",UC_RISCV_REG_HPMCOUNTER30},{"HPMCOUNTER31",UC_RISCV_REG_HPMCOUNTER31},{"CYCLEH",UC_RISCV_REG_CYCLEH},{"TIMEH",UC_RISCV_REG_TIMEH},{"INSTRETH",UC_RISCV_REG_INSTRETH},{"MCYCLE",UC_RISCV_REG_MCYCLE},{"MINSTRET",UC_RISCV_REG_MINSTRET},{"MCYCLEH",UC_RISCV_REG_MCYCLEH},{"MINSTRETH",UC_RISCV_REG_MINSTRETH},{"MVENDORID",UC_RISCV_REG_MVENDORID},{"MARCHID",UC_RISCV_REG_MARCHID},{"MIMPID",UC_RISCV_REG_MIMPID},{"MHARTID",UC_RISCV_REG_MHARTID},{"MSTATUS",UC_RISCV_REG_MSTATUS},{"MISA",UC_RISCV_REG_MISA},{"MEDELEG",UC_RISCV_REG_MEDELEG},{"MIDELEG",UC_RISCV_REG_MIDELEG},{"MIE",UC_RISCV_REG_MIE},{"MTVEC",UC_RISCV_REG_MTVEC},{"MCOUNTEREN",UC_RISCV_REG_MCOUNTEREN},{"MSTATUSH",UC_RISCV_REG_MSTATUSH},{"MUCOUNTEREN",UC_RISCV_REG_MUCOUNTEREN},{"MSCOUNTEREN",UC_RISCV_REG_MSCOUNTEREN},{"MHCOUNTEREN",UC_RISCV_REG_MHCOUNTEREN},{"MSCRATCH",UC_RISCV_REG_MSCRATCH},{"MEPC",UC_RISCV_REG_MEPC},{"MCAUSE",UC_RISCV_REG_MCAUSE},{"MTVAL",UC_RISCV_REG_MTVAL},{"MIP",UC_RISCV_REG_MIP},{"MBADADDR",UC_RISCV_REG_MBADADDR},{"SSTATUS",UC_RISCV_REG_SSTATUS},{"SEDELEG",UC_RISCV_REG_SEDELEG},{"SIDELEG",UC_RISCV_REG_SIDELEG},{"SIE",UC_RISCV_REG_SIE},{"STVEC",UC_RISCV_REG_STVEC},{"SCOUNTEREN",UC_RISCV_REG_SCOUNTEREN},{"SSCRATCH",UC_RISCV_REG_SSCRATCH},{"SEPC",UC_RISCV_REG_SEPC},{"SCAUSE",UC_RISCV_REG_SCAUSE},{"STVAL",UC_RISCV_REG_STVAL},{"SIP",UC_RISCV_REG_SIP},{"SBADADDR",UC_RISCV_REG_SBADADDR},{"SPTBR",UC_RISCV_REG_SPTBR},{"SATP",UC_RISCV_REG_SATP},{"HSTATUS",UC_RISCV_REG_HSTATUS},{"HEDELEG",UC_RISCV_REG_HEDELEG},{"HIDELEG",UC_RISCV_REG_HIDELEG},{"HIE",UC_RISCV_REG_HIE},{"HCOUNTEREN",UC_RISCV_REG_HCOUNTEREN},{"HTVAL",UC_RISCV_REG_HTVAL},{"HIP",UC_RISCV_REG_HIP},{"HTINST",UC_RISCV_REG_HTINST},{"HGATP",UC_RISCV_REG_HGATP},{"PC",UC_RISCV_REG_PC}
    };

    const int numEntries=sizeof(register_array) / sizeof(register_array[0]);
    return index < numEntries ? register_array[index].name : "Invalid";
}

uint64_t register_int_from_name_riscv(const char* reg_name)
{
    for (int i=0;i<MAX_REGISTERS;i++)
    {
        if (strcasecmp(reg_name,register_name_from_int_riscv(i)) == 0)
        {
            return i;
        }
    }
    fprintf(stderr, "Error %s is not a valid register for RISC-V.\n",reg_name);
    fprintf(stderr, "Valid choices are:");
    for (int i=0;i<MAX_REGISTERS;i++)
    {
        fprintf(stderr, "%s ",register_name_from_int_riscv(i));
    }
    fprintf(stderr, "\n");
    my_exit(-1);
    return 666;  /// just here to keep the compiler happy. 
}