#include <string.h>
#include <stdbool.h>
#include <unicorn/unicorn.h>
#include "../utils.h"
#include "../unicorn_consts.h"
#include "../configuration.h"
#include "unicorn_consts_tricore.h"

uint64_t uc_cpu_from_name_tricore(const char* cpu_name)
{
    static unicorn_const_t const cpu_array[]=
    {  
        {"TC1796",UC_CPU_TRICORE_TC1796},{"TC1797",UC_CPU_TRICORE_TC1797},{"TC27X",UC_CPU_TRICORE_TC27X}
    };

    const int numEntries=sizeof(cpu_array) / sizeof(cpu_array[0]);
    for (int i=0;i<numEntries;i++)
    {
        if (strcasecmp(cpu_name,cpu_array[i].name) == 0)
        {
            return cpu_array[i].unicorn_value;
        }

    }
    fprintf(stderr, "Error %s is not a valid CPU for tricore.\n",cpu_name);
    fprintf(stderr, "Valid choices are:");
    for (int i=0;i<numEntries;i++)
    {
        fprintf(stderr, "%s ",cpu_array[i].name);
    }
    fprintf(stderr, "\n");
    my_exit(-1);
    return 666;  /// just here to keep the compiler happy. 
}

/************************************************** uc_reg_from_int_tricore and register_name_from_int_tricore MUST MATCH ************************************/
uint64_t uc_reg_from_int_tricore(uint64_t index)
{
    static unicorn_const_t const register_array[]={
        {"A0",UC_TRICORE_REG_A0},{"A1",UC_TRICORE_REG_A1},{"A2",UC_TRICORE_REG_A2},{"A3",UC_TRICORE_REG_A3},{"A4",UC_TRICORE_REG_A4},{"A5",UC_TRICORE_REG_A5},{"A6",UC_TRICORE_REG_A6},{"A7",UC_TRICORE_REG_A7},{"A8",UC_TRICORE_REG_A8},{"A9",UC_TRICORE_REG_A9},{"A10",UC_TRICORE_REG_A10},{"A11",UC_TRICORE_REG_A11},{"A12",UC_TRICORE_REG_A12},{"A13",UC_TRICORE_REG_A13},{"A14",UC_TRICORE_REG_A14},{"A15",UC_TRICORE_REG_A15},{"D0",UC_TRICORE_REG_D0},{"D1",UC_TRICORE_REG_D1},{"D2",UC_TRICORE_REG_D2},{"D3",UC_TRICORE_REG_D3},{"D4",UC_TRICORE_REG_D4},{"D5",UC_TRICORE_REG_D5},{"D6",UC_TRICORE_REG_D6},{"D7",UC_TRICORE_REG_D7},{"D8",UC_TRICORE_REG_D8},{"D9",UC_TRICORE_REG_D9},{"D10",UC_TRICORE_REG_D10},{"D11",UC_TRICORE_REG_D11},{"D12",UC_TRICORE_REG_D12},{"D13",UC_TRICORE_REG_D13},{"D14",UC_TRICORE_REG_D14},{"D15",UC_TRICORE_REG_D15},{"PCXI",UC_TRICORE_REG_PCXI},{"PSW",UC_TRICORE_REG_PSW},{"PSW_USB_C",UC_TRICORE_REG_PSW_USB_C},{"PSW_USB_V",UC_TRICORE_REG_PSW_USB_V},{"PSW_USB_SV",UC_TRICORE_REG_PSW_USB_SV},{"PSW_USB_AV",UC_TRICORE_REG_PSW_USB_AV},{"PSW_USB_SAV",UC_TRICORE_REG_PSW_USB_SAV},{"PC",UC_TRICORE_REG_PC},{"SYSCON",UC_TRICORE_REG_SYSCON},{"CPU_ID",UC_TRICORE_REG_CPU_ID},{"BIV",UC_TRICORE_REG_BIV},{"BTV",UC_TRICORE_REG_BTV},{"ISP",UC_TRICORE_REG_ISP},{"ICR",UC_TRICORE_REG_ICR},{"FCX",UC_TRICORE_REG_FCX},{"LCX",UC_TRICORE_REG_LCX},{"COMPAT",UC_TRICORE_REG_COMPAT},{"DPR0_U",UC_TRICORE_REG_DPR0_U},{"DPR1_U",UC_TRICORE_REG_DPR1_U},{"DPR2_U",UC_TRICORE_REG_DPR2_U},{"DPR3_U",UC_TRICORE_REG_DPR3_U},{"DPR0_L",UC_TRICORE_REG_DPR0_L},{"DPR1_L",UC_TRICORE_REG_DPR1_L},{"DPR2_L",UC_TRICORE_REG_DPR2_L},{"DPR3_L",UC_TRICORE_REG_DPR3_L},{"CPR0_U",UC_TRICORE_REG_CPR0_U},{"CPR1_U",UC_TRICORE_REG_CPR1_U},{"CPR2_U",UC_TRICORE_REG_CPR2_U},{"CPR3_U",UC_TRICORE_REG_CPR3_U},{"CPR0_L",UC_TRICORE_REG_CPR0_L},{"CPR1_L",UC_TRICORE_REG_CPR1_L},{"CPR2_L",UC_TRICORE_REG_CPR2_L},{"CPR3_L",UC_TRICORE_REG_CPR3_L},{"DPM0",UC_TRICORE_REG_DPM0},{"DPM1",UC_TRICORE_REG_DPM1},{"DPM2",UC_TRICORE_REG_DPM2},{"DPM3",UC_TRICORE_REG_DPM3},{"CPM0",UC_TRICORE_REG_CPM0},{"CPM1",UC_TRICORE_REG_CPM1},{"CPM2",UC_TRICORE_REG_CPM2},{"CPM3",UC_TRICORE_REG_CPM3},{"MMU_CON",UC_TRICORE_REG_MMU_CON},{"MMU_ASI",UC_TRICORE_REG_MMU_ASI},{"MMU_TVA",UC_TRICORE_REG_MMU_TVA},{"MMU_TPA",UC_TRICORE_REG_MMU_TPA},{"MMU_TPX",UC_TRICORE_REG_MMU_TPX},{"MMU_TFA",UC_TRICORE_REG_MMU_TFA},{"BMACON",UC_TRICORE_REG_BMACON},{"SMACON",UC_TRICORE_REG_SMACON},{"DIEAR",UC_TRICORE_REG_DIEAR},{"DIETR",UC_TRICORE_REG_DIETR},{"CCDIER",UC_TRICORE_REG_CCDIER},{"MIECON",UC_TRICORE_REG_MIECON},{"PIEAR",UC_TRICORE_REG_PIEAR},{"PIETR",UC_TRICORE_REG_PIETR},{"CCPIER",UC_TRICORE_REG_CCPIER},{"DBGSR",UC_TRICORE_REG_DBGSR},{"EXEVT",UC_TRICORE_REG_EXEVT},{"CREVT",UC_TRICORE_REG_CREVT},{"SWEVT",UC_TRICORE_REG_SWEVT},{"TR0EVT",UC_TRICORE_REG_TR0EVT},{"TR1EVT",UC_TRICORE_REG_TR1EVT},{"DMS",UC_TRICORE_REG_DMS},{"DCX",UC_TRICORE_REG_DCX},{"DBGTCR",UC_TRICORE_REG_DBGTCR},{"CCTRL",UC_TRICORE_REG_CCTRL},{"CCNT",UC_TRICORE_REG_CCNT},{"ICNT",UC_TRICORE_REG_ICNT},{"M1CNT",UC_TRICORE_REG_M1CNT},{"M2CNT",UC_TRICORE_REG_M2CNT},{"M3CNT",UC_TRICORE_REG_M3CNT}
        };

    /* alias registers
    UC_TRICORE_REG_GA0 = UC_TRICORE_REG_A0, UC_TRICORE_REG_GA1 = UC_TRICORE_REG_A1, UC_TRICORE_REG_GA8 = UC_TRICORE_REG_A8, UC_TRICORE_REG_GA9 = UC_TRICORE_REG_A9, UC_TRICORE_REG_SP = UC_TRICORE_REG_A10, UC_TRICORE_REG_LR = UC_TRICORE_REG_A11, UC_TRICORE_REG_IA = UC_TRICORE_REG_A15, UC_TRICORE_REG_ID = UC_TRICORE_REG_D15,
    */
    const int numEntries=sizeof(register_array) / sizeof(register_array[0]);
    return index < numEntries ? register_array[index].unicorn_value : UC_TRICORE_REG_INVALID;
}
const char* register_name_from_int_tricore(uint64_t index)
{
    static unicorn_const_t const register_array[]={
        {"A0",UC_TRICORE_REG_A0},{"A1",UC_TRICORE_REG_A1},{"A2",UC_TRICORE_REG_A2},{"A3",UC_TRICORE_REG_A3},{"A4",UC_TRICORE_REG_A4},{"A5",UC_TRICORE_REG_A5},{"A6",UC_TRICORE_REG_A6},{"A7",UC_TRICORE_REG_A7},{"A8",UC_TRICORE_REG_A8},{"A9",UC_TRICORE_REG_A9},{"A10",UC_TRICORE_REG_A10},{"A11",UC_TRICORE_REG_A11},{"A12",UC_TRICORE_REG_A12},{"A13",UC_TRICORE_REG_A13},{"A14",UC_TRICORE_REG_A14},{"A15",UC_TRICORE_REG_A15},{"D0",UC_TRICORE_REG_D0},{"D1",UC_TRICORE_REG_D1},{"D2",UC_TRICORE_REG_D2},{"D3",UC_TRICORE_REG_D3},{"D4",UC_TRICORE_REG_D4},{"D5",UC_TRICORE_REG_D5},{"D6",UC_TRICORE_REG_D6},{"D7",UC_TRICORE_REG_D7},{"D8",UC_TRICORE_REG_D8},{"D9",UC_TRICORE_REG_D9},{"D10",UC_TRICORE_REG_D10},{"D11",UC_TRICORE_REG_D11},{"D12",UC_TRICORE_REG_D12},{"D13",UC_TRICORE_REG_D13},{"D14",UC_TRICORE_REG_D14},{"D15",UC_TRICORE_REG_D15},{"PCXI",UC_TRICORE_REG_PCXI},{"PSW",UC_TRICORE_REG_PSW},{"PSW_USB_C",UC_TRICORE_REG_PSW_USB_C},{"PSW_USB_V",UC_TRICORE_REG_PSW_USB_V},{"PSW_USB_SV",UC_TRICORE_REG_PSW_USB_SV},{"PSW_USB_AV",UC_TRICORE_REG_PSW_USB_AV},{"PSW_USB_SAV",UC_TRICORE_REG_PSW_USB_SAV},{"PC",UC_TRICORE_REG_PC},{"SYSCON",UC_TRICORE_REG_SYSCON},{"CPU_ID",UC_TRICORE_REG_CPU_ID},{"BIV",UC_TRICORE_REG_BIV},{"BTV",UC_TRICORE_REG_BTV},{"ISP",UC_TRICORE_REG_ISP},{"ICR",UC_TRICORE_REG_ICR},{"FCX",UC_TRICORE_REG_FCX},{"LCX",UC_TRICORE_REG_LCX},{"COMPAT",UC_TRICORE_REG_COMPAT},{"DPR0_U",UC_TRICORE_REG_DPR0_U},{"DPR1_U",UC_TRICORE_REG_DPR1_U},{"DPR2_U",UC_TRICORE_REG_DPR2_U},{"DPR3_U",UC_TRICORE_REG_DPR3_U},{"DPR0_L",UC_TRICORE_REG_DPR0_L},{"DPR1_L",UC_TRICORE_REG_DPR1_L},{"DPR2_L",UC_TRICORE_REG_DPR2_L},{"DPR3_L",UC_TRICORE_REG_DPR3_L},{"CPR0_U",UC_TRICORE_REG_CPR0_U},{"CPR1_U",UC_TRICORE_REG_CPR1_U},{"CPR2_U",UC_TRICORE_REG_CPR2_U},{"CPR3_U",UC_TRICORE_REG_CPR3_U},{"CPR0_L",UC_TRICORE_REG_CPR0_L},{"CPR1_L",UC_TRICORE_REG_CPR1_L},{"CPR2_L",UC_TRICORE_REG_CPR2_L},{"CPR3_L",UC_TRICORE_REG_CPR3_L},{"DPM0",UC_TRICORE_REG_DPM0},{"DPM1",UC_TRICORE_REG_DPM1},{"DPM2",UC_TRICORE_REG_DPM2},{"DPM3",UC_TRICORE_REG_DPM3},{"CPM0",UC_TRICORE_REG_CPM0},{"CPM1",UC_TRICORE_REG_CPM1},{"CPM2",UC_TRICORE_REG_CPM2},{"CPM3",UC_TRICORE_REG_CPM3},{"MMU_CON",UC_TRICORE_REG_MMU_CON},{"MMU_ASI",UC_TRICORE_REG_MMU_ASI},{"MMU_TVA",UC_TRICORE_REG_MMU_TVA},{"MMU_TPA",UC_TRICORE_REG_MMU_TPA},{"MMU_TPX",UC_TRICORE_REG_MMU_TPX},{"MMU_TFA",UC_TRICORE_REG_MMU_TFA},{"BMACON",UC_TRICORE_REG_BMACON},{"SMACON",UC_TRICORE_REG_SMACON},{"DIEAR",UC_TRICORE_REG_DIEAR},{"DIETR",UC_TRICORE_REG_DIETR},{"CCDIER",UC_TRICORE_REG_CCDIER},{"MIECON",UC_TRICORE_REG_MIECON},{"PIEAR",UC_TRICORE_REG_PIEAR},{"PIETR",UC_TRICORE_REG_PIETR},{"CCPIER",UC_TRICORE_REG_CCPIER},{"DBGSR",UC_TRICORE_REG_DBGSR},{"EXEVT",UC_TRICORE_REG_EXEVT},{"CREVT",UC_TRICORE_REG_CREVT},{"SWEVT",UC_TRICORE_REG_SWEVT},{"TR0EVT",UC_TRICORE_REG_TR0EVT},{"TR1EVT",UC_TRICORE_REG_TR1EVT},{"DMS",UC_TRICORE_REG_DMS},{"DCX",UC_TRICORE_REG_DCX},{"DBGTCR",UC_TRICORE_REG_DBGTCR},{"CCTRL",UC_TRICORE_REG_CCTRL},{"CCNT",UC_TRICORE_REG_CCNT},{"ICNT",UC_TRICORE_REG_ICNT},{"M1CNT",UC_TRICORE_REG_M1CNT},{"M2CNT",UC_TRICORE_REG_M2CNT},{"M3CNT",UC_TRICORE_REG_M3CNT}
        };  

    const int numEntries=sizeof(register_array) / sizeof(register_array[0]);
    return index < numEntries ? register_array[index].name : "Invalid";
}
/************************************************** uc_reg_from_int_tricore and register_name_from_int_tricore MUST MATCH ************************************/


uint64_t register_int_from_name_tricore(const char* reg_name)
{
    for (int i=0;i<MAX_REGISTERS;i++)
    {
        if (strcasecmp(reg_name,register_name_from_int_tricore(i)) == 0)
        {
            return i;
        }
    }
    fprintf(stderr, "Error %s is not a valid register for tricore.\n",reg_name);
    fprintf(stderr, "Valid choices are:");
    for (int i=0;i<MAX_REGISTERS;i++)
    {
        fprintf(stderr, "%s ",register_name_from_int_tricore(i));
    }
    fprintf(stderr, "\n");
    my_exit(-1);
    return 666;  /// just here to keep the compiler happy. 
}
